/**
 * Video Extension Tool - Veo (Google)
 *
 * Extend an existing Veo-generated video by ~7 seconds. The new segment continues
 * seamlessly from the final frames of the source video.
 *
 * IMPORTANT: This tool can only extend videos that were generated by Veo.
 * You must pass the video_uri from a previous generateVideo result.
 *
 * Environment Variables:
 *   GEMINI_API_KEY - Google AI API key (injected by AI Hub at runtime)
 *   VEO_MODEL - Model to use (optional, defaults to veo-3.1-fast-generate-preview)
 *
 * Usage:
 *   import { extendVideo } from '/workspace/ai-hub/tools/dist/video-generation/extendVideo.js';
 *
 *   // First generate a video
 *   const genResult = await generateVideo({ prompt: 'A cat walking' });
 *
 *   // Then extend it using the video_uri from the generation result
 *   const result = await extendVideo({
 *     video_uri: genResult.video_uri,  // URI from generateVideo result
 *     prompt: 'The cat jumps onto a table'
 *   });
 *
 *   if (result.success) {
 *     // result.video_url contains the URL to access the extended video
 *     // result.file_path contains the local file path
 *   }
 */

import {
  VideoResponse,
  handleApiError,
  pollForCompletion,
  downloadVideo,
  saveVideo
} from './shared.js';

export interface ExtendVideoInput {
  /**
   * The video URI from a previous Veo generation.
   * This is the internal Google URI returned by generateVideo.
   * Found in the raw API response as generatedSamples[0].video.uri
   *
   * Note: This tool can ONLY extend Veo-generated videos.
   * Local video files cannot be extended.
   */
  video_uri: string;

  /**
   * Text prompt describing what should happen in the extension.
   * Describe the continuation of action, camera movement, etc.
   * Max 1,024 tokens.
   *
   * @example "The bird takes flight and soars over the mountains"
   * @example "Continue the slow zoom while the sun sets further"
   */
  prompt?: string;

  /**
   * Elements to exclude from the video generation.
   * @example "sudden cuts, camera shake, text overlays"
   */
  negative_prompt?: string;

  /**
   * Seed for reproducibility. Same seed + same inputs may produce similar results.
   * Note: Not guaranteed to be deterministic.
   */
  seed?: number;

  /**
   * Control generation of people in the video.
   * @default "allow_adult"
   */
  person_generation?: 'allow_all' | 'allow_adult';
}

export type ExtendVideoResponse = VideoResponse;

/**
 * Extend a Veo-generated video by approximately 7 seconds.
 *
 * IMPORTANT: This can only extend videos generated by Veo. You must pass the
 * video_uri from a previous generateVideo result, not a local file path.
 *
 * The extension continues seamlessly from the final second of the source video.
 * You can extend a video up to 20 times to create longer content (up to ~148 seconds).
 *
 * @param input - The extension parameters including video URI
 * @returns The extended video URL and file path, or error details
 *
 * @example
 * ```typescript
 * // First, generate a video and save its URI
 * const genResult = await generateVideo({
 *   prompt: 'A butterfly landing on a flower'
 * });
 *
 * // The video_uri is available in the response for extension
 * // You'll need to track this URI if you want to extend the video
 *
 * const result = await extendVideo({
 *   video_uri: 'https://generativelanguage.googleapis.com/v1beta/files/...', // URI from generation
 *   prompt: 'The butterfly flaps its wings and takes flight'
 * });
 *
 * if (result.success) {
 *   console.log('Extended video URL:', result.video_url);
 *   console.log('Saved to:', result.file_path);
 * } else {
 *   console.error('Failed:', result.error);
 * }
 * ```
 */
export async function extendVideo(input: ExtendVideoInput): Promise<ExtendVideoResponse> {
  // Get API key from environment
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return {
      success: false,
      error: 'GEMINI_API_KEY environment variable not set. Video generation is not configured.'
    };
  }

  // Get model from environment or use default
  const model = process.env.VEO_MODEL || 'veo-3.1-fast-generate-preview';

  // Validate input
  if (!input.video_uri) {
    return {
      success: false,
      error: 'video_uri is required. This must be the URI from a previous Veo video generation (not a local file path).'
    };
  }

  // Validate that it looks like a Google API URI
  if (!input.video_uri.includes('generativelanguage.googleapis.com')) {
    return {
      success: false,
      error: 'Invalid video_uri. Must be a URI from a previous Veo generation (starts with https://generativelanguage.googleapis.com/...). Local video files cannot be extended.'
    };
  }

  if (input.prompt && input.prompt.length > 4000) {
    return {
      success: false,
      error: 'Prompt is too long. Maximum ~1,024 tokens (approximately 4,000 characters).'
    };
  }

  try {
    // Build the request body using the video URI
    const instances: any = {
      video: {
        uri: input.video_uri
      }
    };

    // Add optional prompt
    if (input.prompt) {
      instances.prompt = input.prompt.trim();
    }

    // Start the video extension (long-running operation)
    const startResponse = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${model}:predictLongRunning?key=${apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          instances: [instances],
          parameters: {
            ...(input.negative_prompt && { negativePrompt: input.negative_prompt }),
            ...(input.seed !== undefined && { seed: input.seed }),
            ...(input.person_generation && { personGeneration: input.person_generation })
          }
        }),
      }
    );

    if (!startResponse.ok) {
      const errorData = await startResponse.json().catch(() => ({}));
      return handleApiError(startResponse, errorData);
    }

    const startResult = await startResponse.json() as any;
    const operationName = startResult.name;

    if (!operationName) {
      return {
        success: false,
        error: 'Failed to start video extension: no operation name returned.'
      };
    }

    // Poll for completion (extensions may take longer)
    const pollResult = await pollForCompletion(operationName, apiKey, 8 * 60 * 1000);
    if (!pollResult.success) {
      return { success: false, error: pollResult.error };
    }

    // Download the video (pass apiKey for authenticated download)
    const videoBuffer = await downloadVideo(pollResult.videoUri, apiKey);
    if ('error' in videoBuffer) {
      return { success: false, error: videoBuffer.error };
    }

    // Save and return (extension adds ~7 seconds, include new URI for further extensions)
    return saveVideo(videoBuffer, 'extended', 7, pollResult.videoUri);

  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error occurred'
    };
  }
}

export default extendVideo;
